<?php
// $Id: privatemsg_rules.module,v 1.2 2010-03-12 15:59:54 berdir Exp $
/**
 * Implementation of hook_rules_privatemsg_message_insert().
 */
function privatemsg_rules_privatemsg_message_insert($message) {
  foreach ($message['recipients'] as $recipient) {
    rules_invoke_event('privatemsg_insert', $message['subject'], $message['body'], $message['author'], $recipient, $message['mid'], $message['thread_id']);
  }
}
?>
